jobs:
  build1:
    docker:
      - image: cyversevice/rstudio-geospatial:latest
    steps:
      - checkout
      - run: rstudio-server version
  build2:
    docker:
      - image: cyversevice/rstudio-geospatial:3.6.0
    steps:
      - checkout
      - run: rstudio-server version
  build3:
    docker:
      - image: cyversevice/rstudio-geospatial:3.5.3
    steps:
      - checkout
      - run: rstudio-server version
  build4:
    docker:
      - image: cyversevice/rstudio-geospatial:3.5.2
    steps:
      - checkout
      - run: rstudio-server version
  build5:
    docker:
      - image: cyversevice/rstudio-geospatial:3.5.1
    steps:
      - checkout
      - run: rstudio-server version
  build6:
    docker:
      - image: cyversevice/rstudio-geospatial:3.5.0
    steps:
      - checkout
      - run: rstudio-server version
  build7:
    docker:
      - image: cyversevice/rstudio-geospatial:3.4.2
    steps:
      - checkout
      - run: rstudio-server version
workflows:
  version: 2
  build1_to_build7:
    jobs:
      - build1
      - build2
      - build3
      - build4
      - build5
      - build6
      - build7
